name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - uses: astral-sh/setup-uv@v5

      - id: sync
        run: uv sync

      - name: format-check
        if: ${{ !cancelled() && steps.sync.outcome == 'success' }}
        run: uv run poe format-check
      - name: lint
        if: ${{ !cancelled() && steps.sync.outcome == 'success' }}
        run: uv run poe lint
      - name: type
        if: ${{ !cancelled() && steps.sync.outcome == 'success' }}
        run: uv run poe type
